In [4]:
import pandas as pd
import numpy as np

In [5]:
path = "../../../../../../../../../../../s/project/gene_embedding/funcrvp_embeddings/"

omics = pd.read_csv(path + 'omics_d256.tsv', sep='\t')

string = pd.read_csv(path + 'STRING_d128.tsv', sep='\t')

string_exp = pd.read_csv(path + 'STRING_EXP_d128.tsv', sep='\t')

orthrus = pd.read_csv('../preprocessed_data/orthrus_processed.csv')

emogi = pd.read_csv("../preprocessed_data/emogi_preprocessed.tsv", sep='\t')

In [6]:
omics

,gene_id,FACT_EMB_0,FACT_EMB_1,FACT_EMB_2,FACT_EMB_3,FACT_EMB_4,FACT_EMB_5,FACT_EMB_6,FACT_EMB_7,FACT_EMB_8,...,FACT_EMB_246,FACT_EMB_247,FACT_EMB_248,FACT_EMB_249,FACT_EMB_250,FACT_EMB_251,FACT_EMB_252,FACT_EMB_253,FACT_EMB_254,FACT_EMB_255
0,ENSG00000000003,-1.193790,-0.038485,0.477347,-1.355883,-1.283844,0.577406,-0.085741,-0.141601,0.929133,...,1.202038,-0.015473,0.732149,-0.470897,0.163932,0.514095,-1.121097,0.353111,-0.375309,0.271749
1,ENSG00000000005,-0.678243,-0.082044,0.628727,-0.036960,-0.327301,-0.132137,-0.658378,0.382881,0.321670,...,0.158936,1.025258,-0.944454,-0.110598,0.059320,-0.250677,-0.524779,-0.302290,0.627002,0.164144
2,ENSG00000000419,0.763473,0.029731,0.157848,-1.063333,-1.121445,0.855230,0.054342,0.782584,0.679390,...,0.215326,-0.662693,0.154820,0.359877,-0.675248,-0.293355,-0.355871,0.380746,-0.834603,-0.782095
3,ENSG00000000457,0.500445,0.107114,0.758035,-1.097068,0.355529,0.676653,0.562473,-0.585225,0.680695,...,-0.443879,0.226092,0.258948,0.716421,0.022804,-0.488464,-0.700852,-0.285765,0.137165,-0.220267
4,ENSG00000000460,0.085451,0.300662,-0.520867,-0.111104,0.116884,1.271965,0.750282,-0.769611,0.652003,...,-0.781987,-0.538280,-1.022490,-0.261985,-0.225361,0.223187,-0.840165,1.048801,-0.219930,-0.667091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19380,ENSG00000280178,0.151255,0.066157,0.085184,-0.053143,-0.270811,0.211693,-0.401942,0.048608,0.396584,...,0.036106,0.029502,-0.247412,-0.039378,-0.355921,-0.143174,-0.001159,0.033741,-0.136875,-0.467921
19381,ENSG00000280253,0.139209,0.173939,-0.025301,0.197056,-0.086932,0.248732,-0.317894,0.000547,0.264560,...,0.139947,-0.031823,-0.109894,0.097934,-0.243768,-0.176109,-0.002984,-0.027844,0.069011,-0.645361
19382,ENSG00000280267,-0.799880,-0.290801,0.281187,-0.347249,-0.004650,0.019152,0.336727,0.289013,-0.390199,...,-0.213539,-0.293435,-0.636833,0.811885,-0.119030,0.375083,0.600217,-0.772333,0.670361,-0.510163
19383,ENSG00000280297,0.125944,0.020628,-0.069116,-0.076246,-0.322970,0.216778,-0.389412,0.208437,0.143095,...,-0.069501,0.155821,-0.123458,0.270595,-0.460678,0.027504,0.098230,-0.058452,0.088184,-0.454670
19384,ENSG00000280433,0.137917,0.355594,-0.161207,-0.017142,-0.096485,0.333895,-0.323954,0.023822,0.129767,...,0.141053,-0.084122,-0.224260,0.109534,-0.150956,-0.119640,0.128425,0.017256,-0.099188,-0.617878

In [7]:
string

,gene_id,node2vec_STRING_0,node2vec_STRING_1,node2vec_STRING_2,node2vec_STRING_3,node2vec_STRING_4,node2vec_STRING_5,node2vec_STRING_6,node2vec_STRING_7,node2vec_STRING_8,...,verse_STRING_118,verse_STRING_119,verse_STRING_120,verse_STRING_121,verse_STRING_122,verse_STRING_123,verse_STRING_124,verse_STRING_125,verse_STRING_126,verse_STRING_127
0,ENSG00000000003,0.048727,-0.023597,-0.101857,0.197629,-0.259518,0.094224,-0.093681,0.224271,0.225202,...,0.010758,0.152211,-0.446614,-0.609316,0.048469,-0.345373,0.084644,-0.292260,-0.209134,-0.187170
1,ENSG00000000005,0.053368,-0.136473,-0.123004,-0.006521,-0.405079,0.067977,-0.238956,0.323162,0.265277,...,-0.338006,-0.065637,-0.473493,0.092504,0.647252,0.236720,-0.059055,-0.437784,0.424896,0.081466
2,ENSG00000000419,-0.003352,-0.058923,-0.224524,0.168674,-0.316835,0.187886,-0.104933,0.271728,0.354803,...,0.000064,-0.005252,-0.553069,-0.197086,0.131157,-0.008161,0.117704,-0.536833,0.337639,-0.223410
3,ENSG00000000457,-0.060964,0.111577,-0.159858,0.109212,-0.359285,0.151157,-0.178562,0.277919,0.237688,...,-0.336149,-0.049335,-1.122443,0.185830,0.549410,-0.002294,-0.026105,-0.130770,0.273657,0.029464
4,ENSG00000000460,0.267476,0.140644,-0.020111,-0.093544,-0.279677,0.203694,-0.195566,0.429884,0.187878,...,-0.224768,-0.092609,-0.717079,-0.086540,0.673256,-0.530063,0.080660,-0.496925,0.152986,-0.484493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19380,ENSG00000280178,0.010691,-0.037104,-0.133343,0.126059,-0.277243,0.135169,-0.136408,0.316900,0.221641,...,0.052874,-0.075494,-0.343877,0.043701,0.430341,0.035688,0.042674,0.110871,0.436965,-0.241741
19381,ENSG00000280253,-0.075741,0.055031,-0.137354,0.083788,-0.211244,0.033501,-0.272419,0.262333,0.316598,...,-0.516422,-0.122142,-1.007227,-0.145895,0.695526,-0.275660,0.247861,0.112234,0.658723,-0.156475
19382,ENSG00000280267,0.015616,-0.006319,-0.115307,0.118914,-0.306390,0.113326,-0.151365,0.317327,0.260113,...,0.036550,-0.154272,-0.438889,-0.869450,-0.027599,-0.375876,0.054213,-0.345068,-0.162094,0.400044
19383,ENSG00000280297,0.049222,-0.017365,-0.158480,0.195921,-0.389993,0.128805,-0.058590,0.297706,0.248952,...,-0.047023,-0.388763,-0.643482,-0.241741,0.322853,0.107635,0.205680,-0.563593,0.155382,-0.306972
19384,ENSG00000280433,-0.163721,0.164751,-0.232184,0.228675,-0.430493,0.231514,-0.291183,0.255599,0.292068,...,-0.396269,0.047511,-0.605342,-0.079299,0.201933,-0.007060,-0.256862,-0.464566,0.372548,0.213596

In [8]:
string_exp

,gene_id,node2vec_STRING_EXP_0,node2vec_STRING_EXP_1,node2vec_STRING_EXP_2,node2vec_STRING_EXP_3,node2vec_STRING_EXP_4,node2vec_STRING_EXP_5,node2vec_STRING_EXP_6,node2vec_STRING_EXP_7,node2vec_STRING_EXP_8,...,verse_STRING_EXP_118,verse_STRING_EXP_119,verse_STRING_EXP_120,verse_STRING_EXP_121,verse_STRING_EXP_122,verse_STRING_EXP_123,verse_STRING_EXP_124,verse_STRING_EXP_125,verse_STRING_EXP_126,verse_STRING_EXP_127
0,ENSG00000000003,0.116546,-0.279824,-0.112550,-0.459303,-0.239372,0.186485,0.264236,0.017883,-0.244099,...,-0.852502,0.849152,0.347221,0.958687,-0.632295,0.173431,-0.274903,-1.002037,-0.189800,0.511142
1,ENSG00000000005,-0.014115,-0.338361,-0.077789,-0.402543,-0.457482,0.216110,0.282357,-0.012062,-0.235869,...,-0.710637,0.767541,0.471644,1.213388,-0.263752,0.252265,-0.171008,-1.065229,-0.152363,0.165927
2,ENSG00000000419,0.302636,0.072656,0.158833,-0.201725,0.003735,-0.320876,0.016339,-0.204459,-0.035872,...,-1.040879,1.055397,-0.563956,1.255999,-0.502084,-0.019668,-0.580033,-0.575159,-0.107873,-0.321708
3,ENSG00000000457,0.154597,-0.470136,-0.006066,-0.251336,-0.003624,-0.191942,-0.000935,-0.079171,-0.066484,...,-0.972075,0.814683,-0.414577,1.192199,-0.399942,0.064400,-0.782525,-0.546478,-0.127678,-0.087233
4,ENSG00000000460,0.115192,-0.350561,0.111642,-0.008045,-0.064833,-0.267716,-0.032430,-0.096132,0.241286,...,-0.582103,1.072941,0.055873,1.296314,-0.457694,0.530696,-0.773988,-0.519909,0.415668,-0.560442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18706,ENSG00000279911,0.553511,-0.452050,0.115386,-0.164925,-0.698515,-0.013901,0.437031,0.029798,0.226568,...,-0.857214,0.623529,-1.012692,0.449873,-0.576930,-0.159524,0.153431,-0.317198,-0.204590,-0.198232
18707,ENSG00000279941,0.551800,-0.337775,0.168311,-0.171650,-0.674667,0.056141,0.502153,-0.049951,0.167012,...,-0.628170,0.483853,-0.679436,0.656934,-0.696363,-0.056190,0.210962,-0.495034,-0.260303,-0.410423
18708,ENSG00000279973,-0.004263,-0.304996,-0.017881,-0.207718,-0.240242,-0.143710,0.117032,-0.138547,0.017181,...,-0.401178,0.679386,-0.025044,0.483669,-0.385183,-0.202823,-0.053097,-0.777500,0.100124,-0.426191
18709,ENSG00000280165,0.241998,-0.283730,-0.069694,-0.360203,-0.415328,0.261201,0.314894,0.044914,-0.260483,...,-0.708250,0.567962,-0.523431,1.189254,-0.413536,0.558179,-0.009133,-1.040424,0.296491,-0.135329
18710,ENSG00000280253,0.264023,-0.152197,0.068504,-0.112395,-0.323837,0.015469,0.214728,-0.017985,0.072093,...,-0.541022,0.801634,-1.083475,0.328547,-0.759325,0.198397,-0.189828,-0.133223,-0.509287,0.072877

In [9]:
orthrus

,gene_id,0,1,2,3,4,5,6,7,8,...,246,247,248,249,250,251,252,253,254,255
0,ENSG00000186092,-0.067097,-0.037259,0.066265,-0.248337,-0.146096,0.027085,-0.274174,-0.161956,-0.019774,...,0.054242,0.242999,0.133815,-0.233959,-0.092769,0.095052,0.240443,0.458000,-0.305856,0.425528
1,ENSG00000284733,-0.150649,0.019089,0.089471,-0.296814,-0.137837,0.110006,-0.234172,-0.173813,-0.100771,...,0.074931,0.243074,0.104836,-0.261771,-0.040988,0.079414,0.296015,0.542012,-0.324910,0.444035
2,ENSG00000284662,-0.150649,0.019089,0.089471,-0.296814,-0.137837,0.110006,-0.234172,-0.173813,-0.100771,...,0.074931,0.243074,0.104836,-0.261771,-0.040988,0.079414,0.296015,0.542012,-0.324910,0.444035
3,ENSG00000187634,-0.006247,-0.030746,0.007557,-0.341929,-0.275867,-0.058499,-0.329511,-0.167096,0.002317,...,0.058948,0.278398,0.208794,-0.236242,-0.101434,0.067865,0.291427,0.626837,-0.287346,0.327884
4,ENSG00000188976,-0.026891,-0.187528,0.040384,-0.251638,-0.270066,-0.124310,-0.328415,-0.133666,-0.095739,...,0.068438,0.202657,0.150870,-0.125065,-0.039511,0.118810,0.147759,0.584304,-0.341943,0.377747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,ENSG00000249103,-0.072991,0.018168,0.098292,-0.276266,-0.121552,0.063039,-0.284849,-0.200161,0.002627,...,0.091684,0.262072,0.132654,-0.283492,-0.031500,0.169864,0.195653,0.451084,-0.350819,0.399496
19334,ENSG00000231021,-0.001423,-0.078294,0.038144,-0.218092,-0.298642,-0.067565,-0.294970,-0.131460,-0.064628,...,0.026637,0.209670,0.311289,-0.210989,-0.147207,0.040725,0.306769,0.561216,-0.364538,0.331297
19335,ENSG00000227746,-0.076978,0.000924,0.228093,-0.370173,-0.413501,-0.027046,0.143914,-0.242841,0.000517,...,0.106917,0.203670,0.251873,-0.164335,-0.135491,0.140523,0.448572,0.507425,-0.270410,0.354155
19336,ENSG00000233312,-0.077193,-0.000004,0.229113,-0.366380,-0.416127,-0.029360,0.140863,-0.244427,0.002347,...,0.107454,0.205529,0.252420,-0.168219,-0.133900,0.141977,0.445949,0.510589,-0.270349,0.355909
19337,ENSG00000274707,-0.034816,-0.109873,0.031260,-0.237259,-0.212323,0.043359,-0.261847,-0.116702,-0.074381,...,-0.055359,0.209904,0.192059,-0.231228,-0.133682,0.079022,0.253076,0.466747,-0.355033,0.392963

In [10]:
emogi

               gene_id  label      pred
0      ENSG00000100393   True  5.293305
1      ENSG00000133703   True  5.293305
2      ENSG00000155657  False  5.293305
3      ENSG00000284792   True  5.293305
4      ENSG00000039068   True  5.293305
...                ...    ...       ...
13431  ENSG00000266200  False -5.293305
13432  ENSG00000125375  False -5.293305
13433  ENSG00000173662  False -5.293305
13434  ENSG00000197084  False -5.293305
13435  ENSG00000102924  False -5.293305

[13436 rows x 3 columns]